import { Comfortaa } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const comfortaa = Comfortaa({ subsets: ["latin"] });

export const metadata = {
  icons: {
    icon: '/logo.png'
  },
  title: "Marea Tech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={comfortaa.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
